### ISSUE TITLE
NuKeeper throws System.InvalidOperationException on start

### ISSUE THREAD

**Issue by jozefchmelar** [NuKeeperDotNet/NuKeeper#1009]
## 🐛 Bug Report

Nukeeper throws System.InvalidOperationException on start

### Expected behavior
Nukeeper will not throw an exception.

### Reproduction steps
Run
```bash
 nukeeper repo "http://192.168.0.28/repo.name/name.base/_git/name.framework.abstractions" myverylongpersonalaccesstoken --platform "AzureDevOps" --verbosity detailed
```
```csharp
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuKeeper.Commands.RepositoryCommand.TryGetSettingsReader(Uri repoUri, Nullable`1 platform) in d:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Commands\RepositoryCommand.cs:line 87
   at NuKeeper.Commands.RepositoryCommand.PopulateSettings(SettingsContainer settings) in d:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Commands\RepositoryCommand.cs:line 55
   at NuKeeper.Commands.CommandBase.OnExecute() in d:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Commands\CommandBase.cs:line 100
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at NuKeeper.Program.Main(String[] args) in d:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Program.cs:line 35
```

[Link to the line](https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Commands/RepositoryCommand.cs#L87
)
### Configuration
Testing on Azure Devops. Had some issues so I tested it using CLI
I'm checked out on develop branch
Logged in to Git server

**Version:** 0.33.0

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by jozefchmelar** [comment]
I downloaded and debugged the code. The current code [here](https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/Commands/RepositoryCommand.cs#L87) `                return _settingsReaders.Single(s => s.Platform == Platform);` is wrong. 

The code `_settingsReaders.Where(s => s.Platform == Platform).ToList();` returns 3 items with type AzureDevOps

![image](https://user-images.githubusercontent.com/11136013/90475228-5f799880-e127-11ea-8e56-566017d73b0c.png)

For my purposes I was able to use `First(s => s.Platform == Platform)` but obviously that's just my quick fix.
