### ISSUE TITLE
NuGet.Config with private sources is not using

### ISSUE THREAD

**Issue by ykysel** [NuKeeperDotNet/NuKeeper#1035]
Hi.
I'm trying to use version 0.33.0 and can not work with private sources.
Sources are added but not in use (see below). Is this mine configuration problem or bug?

> E:\Agent\1\externals\git\cmd\git.exe config --global user.name NuKeeper
E:\Agent\1\externals\git\cmd\git.exe config --global user.email nukeeper@nukeeper.com
Found tool in cache: nukeeper 0.33.0 x64
**e:\a\1\_tool\nukeeper\0.33.0\x64\NuGet.exe sources add -name projectScoped -source <source> -username nukeeper -password *** -configFile e:\a\1\9\NuGet.config
Package source with Name: projectScoped added successfully.
e:\a\1\_tool\nukeeper\0.33.0\x64\NuGet.exe sources add -name organisationalScoped -source <source> -username nukeeper -password *** -configFile e:\a\1\9\NuGet.config
Package source with Name: organisationalScoped added successfully.**
"C:\Program Files\dotnet\dotnet.exe" e:\a\1\_tool\nukeeper\0.33.0\x64\NuKeeper.dll repo e:\a\1\9\s\src *** --targetBranch origin/play-with-nukeeper -a 0 -m 100 -c minor -n --useprerelease Never -v D -f SingleRepositoryOnly --include ^<LibraryName>.
Matched uri '<Organization url>' to collaboration platform 'AzureDevOps'
FindPushFork. Fork Mode is SingleRepositoryOnly
2020-09-08T10:29:13Z: Started
GetGitRepositories: Requesting <Project Name>/_apis/git/repositories?api-version=4.1
Using upstream fork as push, for project <Project Name> at <Git Url>
User name missing from profile, falling back to .gitconfig
Git clone <Git Url>, branch default, to C:\Users\svcAzureDevOpsBuild\AppData\Local\Temp\NuKeeper\repo-0753d7e180ea45f0a61f14f326c79b08
0 / 360
36 / 360
72 / 360
108 / 360
144 / 360
180 / 360
216 / 360
252 / 360
288 / 360
324 / 360
360 / 360
Git clone complete
**Reading file C:\Users\svcAzureDevOpsBuild\AppData\Roaming\NuGet\NuGet.Config for package sources
Reading file C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config for package sources
Reading file C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config for package sources
Read [nuget.org] : https://api.nuget.org/v3/index.json from file: 
Read [Microsoft Visual Studio Offline Packages] : file:///C:/Program Files (x86)/Microsoft SDKs/NuGetPackages/ from file: C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\\**
Found 15 packages
....

**Comment by ykysel** [comment]
So, I moved NuGet.Config to the root of repository. Now it's using sources, but throw an error when trying to authenticate it (I use private sources):

> Using C:\Users\svcAzureDevOpsBuild\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll as a credential provider plugin.
Problem starting the plugin 'C:\Users\svcAzureDevOpsBuild\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. Cannot start process because a file name has not been provided.
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at NuGet.Protocol.Plugins.PluginProcess.Start()
   at NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
   at NuGet.Protocol.Plugins.PluginFactory.GetOrCreateAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
   at NuGet.Protocol.Plugins.PluginManager.TryCreatePluginAsync(PluginDiscoveryResult result, OperationClaim requestedOperationClaim, PluginRequestKey requestKey, String packageSourceRepository, JObject serviceIndex, CancellationToken cancellationToken)

**Comment by CrispyDrone** [comment]
Yes, since version 3.4 (?) of nuget cli demands that the NuGet.config is at the root of the repository, you can read more about this [here](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses).

You can use credentials in nuget.config or credential providers, maybe the following links can help you:

+ https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds
+ https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops

I'm not sure how this works with multiple sources, I haven't had to configure something like this myself.

**Comment by Bouke** [comment]
NuGet 3.4 requires NuGet.config in the **solution root**, which can be different from **repository root** in for example repositories with multiple solutions. For example I have the following structure:

```
.
├── README.md
└── Sources
    ├── MySolution.sln
    └── NuGet.Config
```

How can I instruct NuKeeper to work from the `Sources/` directory?

**Comment by Bouke** [comment]
…

**Comment by Bouke** [comment]
I’d like to keep this issue open.
