### ISSUE TITLE
Azure DevOps running "org" command fails to create the PR, throws NullReferenceException 

### ISSUE THREAD

**Issue by spr0ut** [NuKeeperDotNet/NuKeeper#1110]
## 🐛 Bug Report

When running nukeeper with the "org" command in Azure DevOps (hosted agent), the branch(es) are created and pushed, but NuKeeper fails to create the PR and throws a NullReferenceException.

```
Git commit with message '📦 Automatic update of CsvHelper to 27.0.2'
Git push to nukeeper_push/nukeeper-update-CsvHelper-to-27.0.2
GetGitRepositories: Requesting version-test/_apis/git/repositories?api-version=4.1
GetPullRequests: Requesting version-test/_apis/git/repositories/1eb94f14-1adb-45e0-ada9-1ac873db1df3/pullrequests?searchCriteria.sourceRefName=refs%2fheads%2fnukeeper-update-CsvHelper-to-27.0.2&searchCriteria.targetRefName=refs%2fheads%2fmain&api-version=4.1
Updates failed NullReferenceException : Object reference not set to an instance of an object.
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\Packages\PackageUpdater.cs:line 140
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\Packages\PackageUpdater.cs:line 65
Attempted 3 updates and did 0

```

### Expected behavior
PR's are created.

### Reproduction steps
Create sample repo(s) with minimal cs proj file as contents. 
Create YAML pipeline - run nukeeper install and org with PAT token
```
steps:
- script: dotnet tool install nukeeper --global
- script: |
    git config --global user.email user@domain.com
    git config --global user.name NuKeeper
- script: nukeeper org version-test $(PAT) --api https://dev.azure.com/ORG_NAME -v D
```
Observe errror.

### Configuration

**Version:** 0.34.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [X] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by CumpsD** [comment]
Same with Github it seems.

```
Checking if PR exists onto 'https://api.github.com/ xxx/xxx: main <= nukeeper-update-14-packages-DC1C0BF46CE1C6EC900BE0E1A13D0037
Failed on repo xxx NullReferenceException : Object reference not set to an instance of an object.
```

**Comment by raunaknarooka** [comment]
I have the same issue while running nukeeper org in github actions.
Failed on repo xx NullReferenceException : Object reference not set to an instance of an object.
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\Packages\PackageUpdater.cs:line 157
