### ISSUE TITLE
Failure to create PR on BitbucketLocal

### ISSUE THREAD

**Issue by chilloutman** [NuKeeperDotNet/NuKeeper#1149]
## 🐛 Bug   

```
Getting from BitBucketLocal url rest/default-reviewers/1.0/projects/redacted/repos/Redacted/reviewers?sourceRepoId=42&targetRepoId=42&sourceRefId=nukeeper-update-NSwag.AspNetCore-to-13.13.2&targetRefId=master
OpenPullRequest: Json exception
Attempting delete of folder C:\Users\user\AppData\Local\Temp\NuKeeper\repo-4b523d2024cf4fe59489121831e0945f
Deleted folder C:\Users\user\AppData\Local\Temp\NuKeeper\repo-4b523d2024cf4fe59489121831e0945f
Failed on repo redacted NuKeeperException : OpenPullRequest: Json exception
   at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.HandleResponse[T](HttpResponseMessage response, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitbucketLocalRestClient.cs:line 87
   at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.GetResourceOrEmpty[T](String url, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitbucketLocalRestClient.cs:line 47
   at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.GetBitBucketReviewers(String projectName, String repositoryName, Int32 repositoryId, String head, String baseRef, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.Bi
tBucketLocal\BitbucketLocalRestClient.cs:line 143
   at NuKeeper.BitBucketLocal.BitBucketLocalPlatform.OpenPullRequest(ForkData target, PullRequestRequest request, IEnumerable`1 labels) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitBucketLocalPlatform.cs:line 69
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in D:\a\r1\a\_NuKeeper PR Build\drop\Nu
Keeper\Engine\Packages\PackageUpdater.cs:line 159
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\Nu
Keeper\Engine\Packages\PackageUpdater.cs:line 78
   at NuKeeper.Engine.RepositoryUpdater.DoTargetUpdates(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 targetUpdates, NuGetSources sources, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\
Engine\RepositoryUpdater.cs:line 145
   at NuKeeper.Engine.RepositoryUpdater.Run(IGitDriver git, RepositoryData repository, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\RepositoryUpdater.cs:line 112
   at NuKeeper.Engine.GitRepositoryEngine.Run(RepositorySettings repository, GitUsernamePasswordCredentials credentials, SettingsContainer settings, User user) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\GitRepositoryEngine
.cs:line 114
   at NuKeeper.Collaboration.CollaborationEngine.Run(SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Collaboration\CollaborationEngine.cs:line 65
Done at 2021-10-28T13:41:15Z
NuKeeper.Abstractions.NuKeeperException: One or multiple repositories failed to update.
---> NuKeeper.Abstractions.NuKeeperException: OpenPullRequest: Json exception
   at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.HandleResponse[T](HttpResponseMessage response, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitbucketLocalRestClient.cs:line 87
  at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.GetResourceOrEmpty[T](String url, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitbucketLocalRestClient.cs:line 47
   at NuKeeper.BitBucketLocal.BitbucketLocalRestClient.GetBitBucketReviewers(String projectName, String repositoryName, Int32 repositoryId, String head, String baseRef, String caller) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.Bi
tBucketLocal\BitbucketLocalRestClient.cs:line 143
   at NuKeeper.BitBucketLocal.BitBucketLocalPlatform.OpenPullRequest(ForkData target, PullRequestRequest request, IEnumerable`1 labels) in D:\a\r1\a\_NuKeeper PR Build\drop\Nukeeper.BitBucketLocal\BitBucketLocalPlatform.cs:line 69
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in D:\a\r1\a\_NuKeeper PR Build\drop\Nu
Keeper\Engine\Packages\PackageUpdater.cs:line 159
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\Nu
Keeper\Engine\Packages\PackageUpdater.cs:line 78
  at NuKeeper.Engine.RepositoryUpdater.DoTargetUpdates(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 targetUpdates, NuGetSources sources, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\
Engine\RepositoryUpdater.cs:line 145
   at NuKeeper.Engine.RepositoryUpdater.Run(IGitDriver git, RepositoryData repository, SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\RepositoryUpdater.cs:line 112
   at NuKeeper.Engine.GitRepositoryEngine.Run(RepositorySettings repository, GitUsernamePasswordCredentials credentials, SettingsContainer settings, User user) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Engine\GitRepositoryEngine
.cs:line 114
   at NuKeeper.Collaboration.CollaborationEngine.Run(SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Collaboration\CollaborationEngine.cs:line 65
   --- End of inner exception stack trace ---
   at NuKeeper.Collaboration.CollaborationEngine.ThrowIfUnhandledException(ValueTuple`2 unhandledEx) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Collaboration\CollaborationEngine.cs:line 126
   at NuKeeper.Collaboration.CollaborationEngine.Run(SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Collaboration\CollaborationEngine.cs:line 89
   at NuKeeper.Commands.CollaborationPlatformCommand.Run(SettingsContainer settings) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Commands\CollaborationPlatformCommand.cs:line 149
   at NuKeeper.Commands.CommandBase.OnExecute() in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Commands\CommandBase.cs:line 108
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at NuKeeper.Program.Main(String[] args) in D:\a\r1\a\_NuKeeper PR Build\drop\NuKeeper\Program.cs:line 35
```

### Expected behavior

Pull request is created. 

### Reproduction steps

`nukeeper repo` against Bitbucket v7.12.1. 

### Configuration

**Version:** 0.35.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [x] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by chilloutman** [comment]
This problem is actually caused by a proxy on our side and not NuKeeper. Sorry.
