### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by skolima** [NuKeeperDotNet/NuKeeper#305]
For some build server scenarios, being able to run NuKeeper inside a simple Docker container would be quite useful. Currently this seems to fail on trying to use LibGit2Sharp - possibly a libc mismatch?

Minimal Dockerfile:

```
FROM microsoft/dotnet:2.1-sdk
RUN dotnet tool install --global NuKeeper
CMD ["/root/.dotnet/tools/NuKeeper", "mode=repository", "t=github-token", "github_repository_uri=https://github.com/my/repo", "log=Verbose"]
```

Building:
`docker build -t nukeeper .`
Running:
`docker run nukeeper`

Current output:
```
Failed on repo mysamplerepo TypeInitializationException : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
   at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at NuKeeper.Git.LibGit2SharpDriver.Clone(Uri pullEndpoint) in C:\Code\NuKeeper\NuKeeper\Git\LibGit2SharpDriver.cs:line 40
   at NuKeeper.Engine.RepositoryUpdater.GitInit(IGitDriver git, RepositoryData repository) in C:\Code\NuKeeper\NuKeeper\Engine\RepositoryUpdater.cs:line 100
   at NuKeeper.Engine.RepositoryUpdater.Run(IGitDriver git, RepositoryData repository) in C:\Code\NuKeeper\NuKeeper\Engine\RepositoryUpdater.cs:line 49
   at NuKeeper.Engine.GithubRepositoryEngine.Run(RepositorySettings repository, UsernamePasswordCredentials gitCreds, Identity userIdentity) in C:\Code\NuKeeper\NuKeeper\Engine\GithubRepositoryEngine.cs:line 45
```

**Comment by AnthonySteele** [comment]
I saw that error on Amazon Linux. Changing to Ubuntu fixed it. LibGit2Sharp wraps a linux binary that doesn't work on all distros.

**Comment by skolima** [comment]
Related: https://github.com/libgit2/libgit2sharp/pull/1582 (but I'll try other base images first before bumping dependencies to preview)

**Comment by AnthonySteele** [comment]
Well spotted. We will definitely want that code. But for now if it works on Ubuntu I can wait for a release.

**Comment by skolima** [comment]
I've tried the steps from https://github.com/libgit2/libgit2sharp/issues/1533 but while those seemed to work for 2.0-sdk-jessie images, 2.1 moved to newer 2.1-sdk-stretch and I can't get those to work. I'll wait for the updated libgit2sharp.

**Comment by AnthonySteele** [comment]
I had the issue because AWS Linux is apparently closely related to Centos, which is not supported yet.

**Comment by skolima** [comment]
There's also a microsoft-provided base Docker image based on Ubuntu: `2.1-sdk-bionic`. This one works! :-)
