### ISSUE TITLE
Inspecting a project with  multiple target frameworks fails

### ISSUE THREAD

**Issue by skolima** [NuKeeperDotNet/NuKeeper#307]
Failing project: https://github.com/tathamoddie/System.IO.Abstractions

Exception:
```Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: NUnit
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at NuKeeper.Inspection.NuGetApi.BulkPackageLookup.ProcessLookupResult(PackageLookupResult packageLookup, Dictionary`2 result) in C:\Code\NuKeeper\NuKeeper.Inspection\NuGetApi\BulkPackageLookup.cs:line 56
   at NuKeeper.Inspection.NuGetApi.BulkPackageLookup.FindVersionUpdates(IEnumerable`1 packages, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper.Inspection\NuGetApi\BulkPackageLookup.cs:line 42
   at NuKeeper.Inspection.NuGetApi.PackageUpdatesLookup.FindUpdatesForPackages(IReadOnlyCollection`1 packages, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper.Inspection\NuGetApi\PackageUpdatesLookup.cs:line 27
   at NuKeeper.Inspection.UpdateFinder.FindPackageUpdateSets(IFolder workingFolder, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper.Inspection\UpdateFinder.cs:line 40
   at NuKeeper.Local.LocalEngine.GetSortedUpdates(IFolder folder, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper\Local\LocalEngine.cs:line 64
   at NuKeeper.Local.LocalEngine.Run(SettingsContainer settings) in C:\Code\NuKeeper\NuKeeper\Local\LocalEngine.cs:line 45
   at NuKeeper.Program.Main(String[] args) in C:\Code\NuKeeper\NuKeeper\Program.cs:line 28
   at NuKeeper.Program.<Main>(String[] args)```

**Comment by skolima** [comment]
Oh. There's reference to `nunit` in one project and `NUnit` in another. Turns out NuGet is case-insensitive when it comes to lookups, but NuKeeper isn't.

**Comment by skolima** [comment]
Second part of the issue is https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/292 (stale `packages.config` left in the repository).
