### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by AnthonySteele** [NuKeeperDotNet/NuKeeper#308]
If you run NuKeeper in a default user folder, it can abort with an exception:

````
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\anthony.steele\Application Data' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuKeeper.Inspection.Sources.NugetConfigFileReader.ReadNugetSources(IFolder workingFolder) in C:\Code\NuKeeper\NuKeeper.Inspection\Sources\NugetConfigFileReader.cs:line 23

````

It should not crash in this case. Can skip the protected folder and carry on.

**Comment by AnthonySteele** [comment]
Fixed
