### ISSUE TITLE
Crash on Windows-1252

### ISSUE THREAD

**Issue by JornWildt** [NuKeeperDotNet/NuKeeper#365]
When running NuKeeper I get this:

    Using 'inspect' for 'mode'
    Using 'https://api.github.com' for 'github_api_endpoint'
    Using '3' for 'max_pull_requests_per_repository'
    Using '10' for 'max_repositories_changed'
    Using 'verbose' for 'log_level'
    Using 'Major' for 'allowed_version_change'
    Using '7d' for 'min_package_age'
    Using 'PreferFork' for 'fork_mode'
    Using 'Off' for 'report_mode'
    Using 'nukeeper' for 'github_labels'
    Running NuKeeper in inspect mode
    Reading file C:\Projects\F2-main\NuGet.Config for package sources
    Reading file C:\Users\jw\AppData\Roaming\NuGet\NuGet.Config for package sources
    Reading file C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config for package sources
    Read [CBrain] : file://lager1/shared/fabrik/NugetRepository from file: C:\Projects\F2-main\NuGet.Config
    Read [nuget.org] : https://api.nuget.org/v3/index.json from file: C:\Users\jw\AppData\Roaming\NuGet\NuGet.Config
    Read [Microsoft Visual Studio Offline Packages] : file:///C:/Program Files (x86)/Microsoft SDKs/NuGetPackages/ from file: C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

    Unhandled Exception: System.Xml.XmlException: System does not support 'Windows-1252' encoding. Line 1, position 31. ---> System.ArgumentException: 'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
    Parameter name: name
       at System.Text.EncodingTable.internalGetCodePageFromName(String name)
       at System.Text.EncodingTable.GetCodePageFromName(String name)
       at System.Text.Encoding.GetEncoding(String name)
       at System.Xml.XmlTextReaderImpl.CheckEncoding(String newEncodingName)
       --- End of inner exception stack trace ---
       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args, Exception innerException)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg, Exception innerException)
       at System.Xml.XmlTextReaderImpl.CheckEncoding(String newEncodingName)
       at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
       at System.Xml.XmlTextReaderImpl.Read()
       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
       at System.Xml.Linq.XDocument.Load(Stream stream)
       at NuKeeper.Inspection.RepositoryInspection.ProjectFileReader.Read(Stream fileContents, String baseDirectory, String relativePath) in C:\Code\NuKeeper\NuKeeper.Inspection\RepositoryInspection\ProjectFileReader.cs:line 37
       at NuKeeper.Inspection.RepositoryInspection.ProjectFileReader.ReadFile(String baseDirectory, String relativePath) in C:\Code\NuKeeper\NuKeeper.Inspection\RepositoryInspection\ProjectFileReader.cs:line 26
       at NuKeeper.Inspection.RepositoryInspection.RepositoryScanner.<>c__DisplayClass3_0.<FindPackages>b__1(FileInfo f) in C:\Code\NuKeeper\NuKeeper.Inspection\RepositoryInspection\RepositoryScanner.cs:line 33
       at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
       at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at NuKeeper.Inspection.RepositoryInspection.RepositoryScanner.FindAllNuGetPackages(IFolder workingFolder) in C:\Code\NuKeeper\NuKeeper.Inspection\RepositoryInspection\RepositoryScanner.cs:line 19
       at NuKeeper.Inspection.UpdateFinder.FindPackageUpdateSets(IFolder workingFolder, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper.Inspection\UpdateFinder.cs:line 34
       at NuKeeper.Local.LocalEngine.GetSortedUpdates(IFolder folder, NuGetSources sources, VersionChange allowedChange) in C:\Code\NuKeeper\NuKeeper\Local\LocalEngine.cs:line 64
       at NuKeeper.Local.LocalEngine.Run(SettingsContainer settings) in C:\Code\NuKeeper\NuKeeper\Local\LocalEngine.cs:line 45
       at NuKeeper.Program.Main(String[] args) in C:\Code\NuKeeper\NuKeeper\Program.cs:line 28
       at NuKeeper.Program.<Main>(String[] args)

I have absolutely no idea of which file that contains the Windows-1252 encoding.

1) Please print the processed filename when dumping errors like this. 

2) Support Windows-1252 if it makes sense? As I said - I really don't know why this happens.

**Comment by skolima** [comment]
For supporting additional code pages: .NET Core needs a package installed for "exotic" encodings like this. https://www.nuget.org/packages/System.Text.Encoding.CodePages/ `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` and afterwards the code page should work. Agreed we could use a better error message here.
