### ISSUE TITLE
Running as a global tool, NuKeeper fails to find NuGet command line

### ISSUE THREAD

**Issue by skolima** [NuKeeperDotNet/NuKeeper#400]
Running as a dotnet tool, installed not globally, but to a custom path (I'm not sure if this step is relevant)

There's 2 sub-issues to this:

 - NuKeeper looks for `NuGet` to run `.sln` restore even when all the package management will be done with `dotnet package` because we're dealing with a dotnet core project and it won't be used
 - NuKeeper fails to find NuGet command line, as installing as a dotnet tool seems to put the dependencies in different locations than we would expect

```
[08:18:19][Step 1/1] Failed on repo Carnect.Locations.Import Exception : Could not find nuget commandline path: C:\Users\buildagent\.nuget\packages\nuget.commandline
[08:18:19][Step 1/1]    at NuKeeper.Update.Process.NuGetPath.FindNugetInPackagesUnderProfile() in C:\Code\NuKeeper\NuKeeper.Update\Process\NuGetPath.cs:line 50
[08:18:19][Step 1/1]    at NuKeeper.Update.Process.NuGetPath.FindExecutable() in C:\Code\NuKeeper\NuKeeper.Update\Process\NuGetPath.cs:line 19
[08:18:19][Step 1/1]    at NuKeeper.Update.Process.NuGetFileRestoreCommand.Invoke(FileInfo file, NuGetSources sources) in C:\Code\NuKeeper\NuKeeper.Update\Process\NuGetFileRestoreCommand.cs:line 36
[08:18:19][Step 1/1]    at NuKeeper.Update.Process.SolutionsRestore.Restore(IFolder workingFolder, NuGetSources sources) in C:\Code\NuKeeper\NuKeeper.Update\Process\SolutionsRestore.cs:line 22
[08:18:19][Step 1/1]    at NuKeeper.Engine.RepositoryUpdater.DoTargetUpdates(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 targetUpdates, NuGetSources sources) in C:\Code\NuKeeper\NuKeeper\Engine\RepositoryUpdater.cs:line 100
[08:18:19][Step 1/1]    at NuKeeper.Engine.RepositoryUpdater.Run(IGitDriver git, RepositoryData repository) in C:\Code\NuKeeper\NuKeeper\Engine\RepositoryUpdater.cs:line 86
[08:18:19][Step 1/1]    at NuKeeper.Engine.GitHubRepositoryEngine.Run(RepositorySettings repository, UsernamePasswordCredentials gitCreds, Identity userIdentity) in C:\Code\NuKeeper\NuKeeper\Engine\GitHubRepositoryEngine.cs:line 53
```

**Comment by skolima** [comment]
When we've added the solution restore step in https://github.com/NuKeeperDotNet/NuKeeper/pull/135 , the tool was run with `ensureSuccess: false` so that the failure wouldn't block applying updates.

**Comment by skolima** [comment]
There's improvements in the linked pull request, but those still don't solve this issue fully. What's needed now is a way to include the `NuGet.CommandLine` when deploying as global tool. This line is a bit suspicious:

**Comment by skolima** [comment]
Reason why the `NuGet.CommandLine` is not included is likely to be https://github.com/dotnet/cli/issues/7566 - I'll try packing the `NuGet.exe` explicitly.

**Comment by skolima** [comment]
Got the packaging to work - now just need to add a third path to the probing logic.
