### ISSUE TITLE
Azure DevOps parsing error

### ISSUE THREAD

**Issue by phatcher** [NuKeeperDotNet/NuKeeper#528]
Getting an error trying to update a project...

`dotnet run -p C:\Devel\OpenSource\Nukeeper\Nukeeper\NuKeeper.csproj -- repo https://dev.azure.com/atrios/Meerkat/_git/Meerkat {PAT} --include ServiceBus --age 3d -v d`

gives

```
2018-11-15T00:19:14Z: Started
User name missing from profile, falling back to .gitconfig
FindPushFork. Fork Mode is SingleRepositoryOnly
Failed on repo Meerkat NullReferenceException : Object reference not set to an instance of an object.
   at NuKeeper.AzureDevOps.AzureDevOpsRestClient.GetGitRepositories(String projectName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsRestClient.cs:line 49
   at NuKeeper.AzureDevOps.AzureDevOpsPlatform.GetRepositoriesForOrganisation(String projectName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevopsPlatform.cs:line 57
   at NuKeeper.AzureDevOps.AzureDevOpsPlatform.GetUserRepository(String projectName, String repositoryName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevopsPlatform.cs:line 65
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.IsPushableRepo(ForkData originFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 56
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.FindUpstreamRepoOnly(ForkData pullFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 38
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.FindPushFork(String userName, ForkData fallbackFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 32
   at NuKeeper.Engine.GitRepositoryEngine.BuildGitRepositorySpec(RepositorySettings repository, String userName) in C:\Devel\OpenSource\Nukeeper\Nukeeper\Engine\GitRepositoryEngine.cs:line 73
   at NuKeeper.Engine.GitRepositoryEngine.Run(RepositorySettings repository, UsernamePasswordCredentials gitCreds, Identity userIdentity, SettingsContainer settings) in C:\Devel\OpenSource\Nukeeper\Nukeeper\Engine\GitRepositoryEngine.cs:line 42
Done at 2018-11-15T00:19:15Z
```

I don't think it's an invalid PAT as if I change it that give a different error stack trace...

```
Failed on repo Meerkat JsonReaderException : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NuKeeper.AzureDevOps.AzureDevOpsRestClient.GetResorceOrEmpty[T](String url) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsRestClient.cs:line 34
   at NuKeeper.AzureDevOps.AzureDevOpsRestClient.GetGitRepositories(String projectName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsRestClient.cs:line 48
   at NuKeeper.AzureDevOps.AzureDevOpsPlatform.GetRepositoriesForOrganisation(String projectName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevopsPlatform.cs:line 57
   at NuKeeper.AzureDevOps.AzureDevOpsPlatform.GetUserRepository(String projectName, String repositoryName) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevopsPlatform.cs:line 65
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.IsPushableRepo(ForkData originFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 56
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.FindUpstreamRepoOnly(ForkData pullFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 38
   at NuKeeper.AzureDevOps.AzureDevOpsForkFinder.FindPushFork(String userName, ForkData fallbackFork) in C:\Devel\OpenSource\Nukeeper\NuKeeper.AzureDevOps\AzureDevOpsForkFinder.cs:line 32
   at NuKeeper.Engine.GitRepositoryEngine.BuildGitRepositorySpec(RepositorySettings repository, String userName) in C:\Devel\OpenSource\Nukeeper\Nukeeper\Engine\GitRepositoryEngine.cs:line 73
   at NuKeeper.Engine.GitRepositoryEngine.Run(RepositorySettings repository, UsernamePasswordCredentials gitCreds, Identity userIdentity, SettingsContainer settings) in C:\Devel\OpenSource\Nukeeper\Nukeeper\Engine\GitRepositoryEngine.cs:line 42
```

**Comment by MarcBruins** [comment]
Thanks for trying out the latest AzureDevOps bits!

I've tried your command on my own repository (which doesn't have ServiceBug packages) and it works fine. Is there a reproducable scenario that you could give us(which doesn't have a private repo)?

**Comment by shep1987** [comment]
Is it possible to get a redacted version of the JSon before we try to parse it please, my top suspect is the size prop in the AzureRepository class.

**Comment by phatcher** [comment]
@shep1987 Which json do you want - the response from GetResorceOrEmpty<ProjectResource>($"/_apis/projects"); ?

**Comment by MarcBruins** [comment]
Yes i think that is a thing we still need to do. Make it more fault tolerant and make it transparant what is going wrong. Can you join the gitter channel to discuss: https://gitter.im/NuKeeperDotNet/Lobby ?

**Comment by MarcBruins** [comment]
Can you close this issue @phatcher

**Comment by phatcher** [comment]
I can do but I was going to keep it open as a placeholder for the resiliency changes
