### ISSUE TITLE
Repeated out of memory exception

### ISSUE THREAD

**Issue by Richiban** [NuKeeperDotNet/NuKeeper#627]
On our build agent we're getting very frequent OutOfMemoryExceptions when running NuKeeper in repo mode. It seems to occur more or less frequently depending on which solution we run it on.

Here's an example: 

```
[12:07:02][Step 5/5] Found NuGet.exe: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe
[12:07:02][Step 5/5] In path C:\BuildAgent\work\98739dabf3b446bd\FunctionalTests, running command: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe update packages.config -Id XXXXXXXX.Sql -Version 1.23.101 -Source https://proget.services.kingsway.asos.com/nuget/ASOSPackages -Source https://proget.services.kingsway.asos.com/nuget/ASOS -Source https://XXXXXXXX.pkgs.visualstudio.com/_packaging/AsosMarketplace/nuget/v2 -Source https://api.nuget.org/v3/index.json
[12:14:41][Step 5/5] Updates failed OutOfMemoryException : Insufficient memory to continue the execution of the program.
[12:14:42][Step 5/5] Error message is logged
[12:14:41][Step 5/5]    at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
[12:14:41][Step 5/5] Attempted 3 updates and did 0
[12:14:41][Step 5/5] Done at 2018-12-27T12:14:41Z
[12:14:41][Step 5/5]    at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
[12:14:41][Step 5/5]    at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
[12:14:41][Step 5/5]    at System.IO.StreamReader.ReadToEndAsyncInternal()
[12:14:41][Step 5/5]    at NuKeeper.Update.ProcessRunner.ExternalProcess.Run(String workingDirectory, String command, String arguments, Boolean ensureSuccess) in /home/vsts/work/r1/a/drop/NuKeeper.Update/ProcessRunner/ExternalProcess.cs:line 47
[12:14:41][Step 5/5]    at NuKeeper.Update.Process.NuGetUpdatePackageCommand.Invoke(PackageInProject currentPackage, NuGetVersion newVersion, PackageSource packageSource, NuGetSources allSources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/Process/NuGetUpdatePackageCommand.cs:line 48
[12:14:41][Step 5/5]    at NuKeeper.Update.UpdateRunner.Update(PackageUpdateSet updateSet, NuGetSources sources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/UpdateRunner.cs:line 52
[12:14:41][Step 5/5]    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 77
[12:14:41][Step 5/5]    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 46
[12:14:42][Step 5/5] Process exited with code 0
```

**Comment by AnthonySteele** [comment]
That's interesting and novel! Are there any more details if you run NuKeeper with detailed logging, i.e. `-v d`

It looks as if it's failing when NuKeeper runs `NuGet.exe` in order to perform an update. Is there any reason why this would produce a very large amount of output?

**Comment by Richiban** [comment]
We're already running with detailed logging; that tail end of the log looked the most interesting. 

If it helps, here are the few dozen lines above that in the output:

```
[12:06:47][Step 5/5] Wrote report for 54 updates
[12:06:47][Step 5/5] Resorted 54 packages by dependencies, first change is Microsoft.NETCore.Platforms moved to position 0 from 48.
[12:06:47][Step 5/5] Filtered by Include '^XXXXXXXX.' from 54 to 3
[12:06:47][Step 5/5] GetGitRepositories: Requesting Marketplace/_apis/git/repositories?api-version=4.1
[12:06:47][Step 5/5] GetGitRepositories: Requesting Marketplace/_apis/git/repositories?api-version=4.1
[12:06:47][Step 5/5] GetGitRepositories: Requesting Marketplace/_apis/git/repositories?api-version=4.1
[12:06:47][Step 5/5] GetRepositoryRefs: Requesting Marketplace/_apis/git/repositories/204f3eb0-a153-450b-be0c-f0c38f8dadde/refs?api-version=4.1
[12:06:47][Step 5/5] GetRepositoryRefs: Requesting Marketplace/_apis/git/repositories/204f3eb0-a153-450b-be0c-f0c38f8dadde/refs?api-version=4.1
[12:06:47][Step 5/5] GetRepositoryRefs: Requesting Marketplace/_apis/git/repositories/204f3eb0-a153-450b-be0c-f0c38f8dadde/refs?api-version=4.1
[12:06:47][Step 5/5] No branch found for Marketplace / XXXXXXXX.Crm.Facebook / nukeeper-update-XXXXXXXX.Customer.Profile.DataSetUpUtilities-to-1.1.66
[12:06:47][Step 5/5] No branch found for Marketplace / XXXXXXXX.Crm.Facebook / nukeeper-update-XXXXXXXX.Sql-to-1.23.101
[12:06:47][Step 5/5] No branch found for Marketplace / XXXXXXXX.Crm.Facebook / nukeeper-update-XXXXXXXX.Testing.TemporaryDatabase-to-1.7.15
[12:06:47][Step 5/5] Selection of package updates: 54 candidates, filtered to 3
[12:06:47][Step 5/5] Selected package update of XXXXXXXX.Sql to 1.23.101
[12:06:47][Step 5/5] Selected package update of XXXXXXXX.Customer.Profile.DataSetUpUtilities to 1.1.66
[12:06:47][Step 5/5] Selected package update of XXXXXXXX.Testing.TemporaryDatabase to 1.7.15
[12:06:47][Step 5/5] Nuget restore on C:\BuildAgent\work\98739dabf3b446bd XXXXXXXX.Crm.Facebook.sln
[12:06:47][Step 5/5] Found NuGet.exe: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe
[12:06:47][Step 5/5] In path C:\BuildAgent\work\98739dabf3b446bd, running command: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe restore XXXXXXXX.Crm.Facebook.sln -Source https://proget.services.kingsway.asos.com/nuget/ASOSPackages -Source https://proget.services.kingsway.asos.com/nuget/ASOS -Source https://XXXXXXXX.pkgs.visualstudio.com/_packaging/AsosMarketplace/nuget/v2 -Source https://api.nuget.org/v3/index.json
[12:07:00][Step 5/5] Nuget restore on XXXXXXXX.Crm.Facebook.sln complete
[12:07:00][Step 5/5] Updating'XXXXXXXX.Sql' from 1.5.37 to 1.23.101 in 1 projects
[12:07:00][Step 5/5] Git checkout 'master'
[12:07:00][Step 5/5] Using branch name: 'nukeeper-update-XXXXXXXX.Sql-to-1.23.101'
[12:07:00][Step 5/5] Git checkout new branch 'nukeeper-update-XXXXXXXX.Sql-to-1.23.101'
[12:07:00][Step 5/5] Sorted 1 projects by dependencies but no change made
[12:07:00][Step 5/5] Updating 'XXXXXXXX.Sql' to 1.23.101 in 1 projects
[12:07:00][Step 5/5] Nuget restore on C:\BuildAgent\work\98739dabf3b446bd\FunctionalTests packages.config
[12:07:00][Step 5/5] Found NuGet.exe: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe
[12:07:00][Step 5/5] In path C:\BuildAgent\work\98739dabf3b446bd\FunctionalTests, running command: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe restore packages.config -Source https://proget.services.kingsway.asos.com/nuget/ASOSPackages -Source https://proget.services.kingsway.asos.com/nuget/ASOS -Source https://XXXXXXXX.pkgs.visualstudio.com/_packaging/AsosMarketplace/nuget/v2 -Source https://api.nuget.org/v3/index.json
[12:07:02][Step 5/5] Command C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe failed with exit code: 1
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory.
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] Nuget restore failed on C:\BuildAgent\work\98739dabf3b446bd\FunctionalTests packages.config:
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory.
[12:07:02][Step 5/5] 
[12:07:02][Step 5/5] Found NuGet.exe: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe
[12:07:02][Step 5/5] In path C:\BuildAgent\work\98739dabf3b446bd\FunctionalTests, running command: C:\Users\ContainerAdministrator\.dotnet\tools\.store\nukeeper\0.11.0\nukeeper\0.11.0\tools\netcoreapp2.1\any\NuGet.exe update packages.config -Id XXXXXXXX.Sql -Version 1.23.101 -Source https://proget.services.kingsway.asos.com/nuget/ASOSPackages -Source https://proget.services.kingsway.asos.com/nuget/ASOS -Source https://XXXXXXXX.pkgs.visualstudio.com/_packaging/AsosMarketplace/nuget/v2 -Source https://api.nuget.org/v3/index.json
[12:14:41][Step 5/5] Updates failed OutOfMemoryException : Insufficient memory to continue the execution of the program.
[12:14:42][Step 5/5] Error message is logged
[12:14:41][Step 5/5]    at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
[12:14:41][Step 5/5] Attempted 3 updates and did 0
[12:14:41][Step 5/5] Done at 2018-12-27T12:14:41Z
[12:14:41][Step 5/5]    at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
[12:14:41][Step 5/5]    at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
[12:14:41][Step 5/5]    at System.IO.StreamReader.ReadToEndAsyncInternal()
[12:14:41][Step 5/5]    at NuKeeper.Update.ProcessRunner.ExternalProcess.Run(String workingDirectory, String command, String arguments, Boolean ensureSuccess) in /home/vsts/work/r1/a/drop/NuKeeper.Update/ProcessRunner/ExternalProcess.cs:line 47
[12:14:41][Step 5/5]    at NuKeeper.Update.Process.NuGetUpdatePackageCommand.Invoke(PackageInProject currentPackage, NuGetVersion newVersion, PackageSource packageSource, NuGetSources allSources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/Process/NuGetUpdatePackageCommand.cs:line 48
[12:14:41][Step 5/5]    at NuKeeper.Update.UpdateRunner.Update(PackageUpdateSet updateSet, NuGetSources sources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/UpdateRunner.cs:line 52
[12:14:41][Step 5/5]    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 77
[12:14:41][Step 5/5]    at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 46
[12:14:42][Step 5/5] Process exited with code 0
```

I've got no idea why NuGet would produce a huge amount or output... but the build does hang when it gets to this step (just before the exception). It sits there for about 2 minutes before barfing, unfortunately with no more output.

---

P.S. Glad I can give you something new to worry about!

**Comment by Richiban** [comment]
FYI, This is the command we're running:

```
~\.dotnet\tools\nukeeper.exe repo . %NuKeeper.AzureDevOps.AccessToken% --include ^XXXXXXXX. --change minor --age 0 --verbosity Detailed
```

**Comment by Richiban** [comment]
Hmm... after trying to update this package manually on my machine using the NuGet command line, I see that I am presented with this prompt:

````
File Conflict.
File 'Asos.Marketplace.Sql.dacpac' already exists in project 'FunctionalTests.csproj'. Do you want to overwrite it?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All ?
```

Could this prompt be what is causing the process to hang and eventually run out of memory?

**Comment by Richiban** [comment]
If this is the case then we need an extra config parameter to NuKeeper that we can pass through to Nuget's `-FileConflictAction`

**Comment by AnthonySteele** [comment]
We should probably default the `-FileConflictAction`. Well spotted.

**Comment by AnthonySteele** [comment]
If you add `-NonInteractive` to that command line, does it still prompt `Do you want to overwrite it` ?

**Comment by Richiban** [comment]
Right, took me a long time to be able to run this test due to NuGet authentication being screwed up on my machine, but I can confirm there's no prompt when `-NonInteractive` is passed to NuGet. The file is simply overwritten (which is, in this case, what we want).

**Comment by MarcBruins** [comment]
Can this be closed now?
