### ISSUE TITLE
"Sequence contains no matching element" exception on first run

### ISSUE THREAD

**Issue by OneCyrus** [NuKeeperDotNet/NuKeeper#664]
we get the following error on Azure Devops with the Nukeeper extension on the first run. Rerun fixes the issue.

```2019-01-24T13:06:43.6764713Z ==============================================================================
2019-01-24T13:06:43.6765138Z Task         : NuKeeper
2019-01-24T13:06:43.6765322Z Description  : Version 0.1.54
2019-01-24T13:06:43.6765428Z Version      : 0.1.54
2019-01-24T13:06:43.6765545Z Author       : NuKeeper
2019-01-24T13:06:43.6765685Z Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
2019-01-24T13:06:43.6765868Z ==============================================================================
2019-01-24T13:06:44.6094085Z [command]D:\VstsBuildAgent\externals\git\cmd\git.exe checkout master
2019-01-24T13:06:44.6095453Z [command]D:\VstsBuildAgent\externals\git\cmd\git.exe pull
2019-01-24T13:06:44.6096662Z [command]D:\VstsBuildAgent\externals\git\cmd\git.exe config --global user.name NuKeeper
2019-01-24T13:06:44.6097979Z [command]D:\VstsBuildAgent\externals\git\cmd\git.exe config --global user.email nukeeper@nukeeper.com
2019-01-24T13:06:44.6157316Z [command]"C:\Program Files\dotnet\dotnet.exe" D:\VstsBuildAgent\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.1.54\bin\NuKeeper.dll repo D:\VstsBuildAgent\_work\33\s *** -p 3
2019-01-24T13:06:45.0636762Z You are not currently on a branch.
2019-01-24T13:06:45.0651434Z Please specify which branch you want to merge with.
2019-01-24T13:06:45.0652621Z See git-pull(1) for details.
2019-01-24T13:06:45.0653087Z 
2019-01-24T13:06:45.0653340Z     git pull <remote> <branch>
2019-01-24T13:06:45.0655884Z 
2019-01-24T13:06:45.4608951Z 
2019-01-24T13:06:46.0066827Z Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
2019-01-24T13:06:46.0068492Z    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
2019-01-24T13:06:46.0068781Z    at NuKeeper.Git.LibGit2SharpDiscoveryDriver.GetCurrentHead(Uri repositoryUri) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper.Git\LibGit2SharpDiscoveryDriver.cs:line 63
2019-01-24T13:06:46.0069137Z    at NuKeeper.AzureDevOps.VstsSettingsReader.CreateSettingsFromLocal(Uri repositoryUri) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper.AzureDevOps\VSTSSettingsReader.cs:line 88
2019-01-24T13:06:46.0069492Z    at NuKeeper.Commands.RepositoryCommand.PopulateSettings(SettingsContainer settings) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper\Commands\RepositoryCommand.cs:line 37
2019-01-24T13:06:46.0069797Z    at NuKeeper.Commands.CommandBase.OnExecute() in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper\Commands\CommandBase.cs:line 84
2019-01-24T13:06:46.0070017Z    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
2019-01-24T13:06:46.0070391Z    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
2019-01-24T13:06:46.0070629Z    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
2019-01-24T13:06:46.0070830Z --- End of stack trace from previous location where exception was thrown ---
2019-01-24T13:06:46.0071124Z    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
2019-01-24T13:06:46.0071307Z    at NuKeeper.Program.Main(String[] args) in C:\Users\marc\Documents\repos\NuKeeper\NuKeeper\Program.cs:line 29
2019-01-24T13:06:46.0775427Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 3762504530
```

**Comment by OneCyrus** [comment]
on one repo a rerun doesn't solve the issue

**Comment by MarcBruins** [comment]
Is there anything special about that repo? We do a `git checkout "YourMainBranch"` does it have a special name or something?

**Comment by OneCyrus** [comment]
no, it happens on all repos. IMHO you shouldn't do a git checkout with the azure devops extension because that's what the agent does anyway before executing tasks.

**Comment by MarcBruins** [comment]
The reason why we do it is because the devops extension checks out a `detached head` from your current master branch. The reason being that with multiple PR's you don't get a weird state, where you do a PR and another person in your team does a PR on the same stuff.

NuKeeper doesn't work with a `detached head` as it doesn't know which branch it should target. It fails here(https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper.Git/LibGit2SharpDiscoveryDriver.cs#L65). If we could make NuKeeper work with a detached head that would be nice, but i'm not sure if you can see if it's a detached head and from which branch that detachead head comes from.

**Comment by OneCyrus** [comment]
there are environment variables which should help here https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops

**Comment by OneCyrus** [comment]
issue was asynchronous git commands in the AzD extension. it's fixed now
