### ISSUE TITLE
Crash with azuredevops extension

### ISSUE THREAD

**Issue by MarcBruins** [NuKeeperDotNet/NuKeeper#677]
When running the azuredevops extension against my test-repo i get the following error:

```
Git Cannot checkout new branch: a branch named 'origin/nukeeper-update-Microsoft.NET.Test.Sdk-to-15.9.0' already exists
Updating'Microsoft.NET.Test.Sdk' from 15.8.0 to 15.9.0 in 1 projects
Selected package update of xunit.runner.visualstudio to 2.4.1
Selected package update of xunit to 2.4.1
Selected package update of Microsoft.NET.Test.Sdk to 15.9.0
Updates failed ArgumentNullException : Value cannot be null.
Parameter name: branch
Attempted 3 updates and did 0
```

Note that the branch doesn't exist, atleast not i can see it in the azuredevops dashboard. We will have to investigate further what is going on. Seems like the branch checkout fail causes this.

**Comment by OneCyrus** [comment]
same issue here. and the detailed logs:

```
Parameter name: branch
   at LibGit2Sharp.BranchUpdater..ctor(Repository repo, Branch branch)
   at LibGit2Sharp.BranchCollection.Update(Branch branch, Action`1[] actions)
   at NuKeeper.Git.LibGit2SharpDriver.Push(String remoteName, String branchName) in C:\temp\NuKeeper\NuKeeper.Git\LibGit2SharpDriver.cs:line 150
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in C:\temp\NuKeeper\NuKeeper\Engine\Packages\PackageUpdater.cs:line 83
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in C:\temp\NuKeeper\NuKeeper\Engine\Packages\PackageUpdater.cs:line 46
```

the issue is with the comparison of the branches. On AzD we get branch names starting with "refs/"
