### ISSUE TITLE
UnAuthorizedException when executing NuKeeper

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper#746]
## 🐛 Bug Report
I'm running NuKeeper from the Azure DevOps extension, since the latest release of NuKeeper (version 0.20.3) I get following exception when running:

```
[command]C:\agents\agent1\_work\_tool\dncs\2.2.202\x64\dotnet.exe C:\agents\agent1\_work\_temp\nukeeper\tools\netcoreapp2.1\any\NuKeeper.dll repo C:\agents\agent1\_work\10\s ******** --targetBranch origin/master -v detailed -c Major -i (MSTest|Microsoft.NET.Test.Sdk|Microsoft.TestPlatform.TestHost) -n
Matched uri 'https://fudura.visualstudio.com/' to collaboration platform 'AzureDevOps'
FindPushFork. Fork Mode is SingleRepositoryOnly
2019-04-20T07:33:35Z: Started
Attempting delete of folder C:\agents\agent1\_work\_temp\NuKeeper\package
Deleted folder C:\agents\agent1\_work\_temp\NuKeeper\package
Attempting delete of folder C:\agents\agent1\_work\_temp\NuKeeper\tools

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\agents\agent1\_work\_temp\NuKeeper\tools\netcoreapp2.1\any\LibGit2Sharp.dll' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at NuKeeper.Inspection.Files.Folder.DeleteDirectoryInternal(String targetDir) in /home/vsts/work/r1/a/drop/NuKeeper.Inspection/Files/Folder.cs:line 68
   at NuKeeper.Inspection.Files.Folder.DeleteDirectoryInternal(String targetDir) in /home/vsts/work/r1/a/drop/NuKeeper.Inspection/Files/Folder.cs:line 74
   at NuKeeper.Inspection.Files.Folder.DeleteDirectoryInternal(String targetDir) in /home/vsts/work/r1/a/drop/NuKeeper.Inspection/Files/Folder.cs:line 74
   at NuKeeper.Inspection.Files.Folder.TryDelete() in /home/vsts/work/r1/a/drop/NuKeeper.Inspection/Files/Folder.cs:line 45
   at NuKeeper.Inspection.Files.FolderFactory.DeleteExistingTempDirs() in /home/vsts/work/r1/a/drop/NuKeeper.Inspection/Files/FolderFactory.cs:line 44
   at NuKeeper.Collaboration.CollaborationEngine.Run(SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Collaboration/CollaborationEngine.cs:line 35
   at NuKeeper.Commands.CollaborationPlatformCommand.Run(SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Commands/CollaborationPlatformCommand.cs:line 116
   at NuKeeper.Commands.CommandBase.OnExecute() in /home/vsts/work/r1/a/drop/NuKeeper/Commands/CommandBase.cs:line 96
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at NuKeeper.Program.Main(String[] args) in /home/vsts/work/r1/a/drop/NuKeeper/Program.cs:line 33
##[debug]task result: Failed
##[error]Error: The process 'C:\agents\agent1\_work\_tool\dncs\2.2.202\x64\dotnet.exe' failed with exit code 3762504530
```

I did setup the Azure DevOps extension properly including checking the oath token checkbox. Maybe we are still making use of the `LibGit2Sharp.dll` while at the same time we want to delete that file. Perhaps we don't dispose of some unmanaged resources? I searched and found one place: https://github.com/NuKeeperDotNet/NuKeeper/pull/747

### Expected behavior
Package updates being offered by pull request from NuKeeper.

### Reproduction steps
Run NuKeeper build step with following `Arguments`:
`-v detailed -c Major -i (MSTest|Microsoft.NET.Test.Sdk|Microsoft.TestPlatform.TestHost) -n`

### Configuration

**NuKeeper Version:** 0.20.3
**NuKeeper Azure DevOps extension Version:** 0.3.4

**Platform if applicable:** 
- [x] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: Github
- [x] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by MaxMommersteeg** [comment]
Issue is still present with release 0.20.4.
