### ISSUE TITLE
error : '.0' is not a valid version string.

### ISSUE THREAD

**Issue by aprice30** [NuKeeperDotNet/NuKeeper#893]
Updating Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions to 3.0.0 from 2.2.0 in 2 places since 1 month ago.

Unhandled Exception: NuKeeper.Abstractions.NuKeeperException: Command dotnet failed with exit code: 1

c:\program files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : '.0' is not a valid version string. (Parameter 'value') [C:\Workspace\cmew\services_diffusion_pkg\test\CME.Workstation.Services.Diffusion.Tests\CME.Workstation.Services.Diffusion.Tests.csproj]

   at NuKeeper.Update.ProcessRunner.ExternalProcess.Run(String workingDirectory, String command, String arguments, Boolean ensureSuccess) in /home/vsts/work/r1/a/drop/NuKeeper.Update/ProcessRunner/ExternalProcess.cs:line 63
   at NuKeeper.Update.Process.DotNetUpdatePackageCommand.Invoke(PackageInProject currentPackage, NuGetVersion newVersion, PackageSource packageSource, NuGetSources allSources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/Process/DotNetUpdatePackageCommand.cs:line 28
   at NuKeeper.Update.UpdateRunner.Update(PackageUpdateSet updateSet, NuGetSources sources) in /home/vsts/work/r1/a/drop/NuKeeper.Update/UpdateRunner.cs:line 52
   at NuKeeper.Local.LocalUpdater.ApplyUpdates(IReadOnlyCollection`1 updates, IFolder workingFolder, NuGetSources sources) in /home/vsts/work/r1/a/drop/NuKeeper/Local/LocalUpdater.cs:line 67
   at NuKeeper.Local.LocalUpdater.ApplyUpdates(IReadOnlyCollection`1 updates, IFolder workingFolder, NuGetSources sources, SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Local/LocalUpdater.cs:line 56
   at NuKeeper.Local.LocalEngine.Run(SettingsContainer settings, Boolean write) in /home/vsts/work/r1/a/drop/NuKeeper/Local/LocalEngine.cs:line 62
   at NuKeeper.Commands.UpdateCommand.Run(SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Commands/UpdateCommand.cs:line 52
   at NuKeeper.Commands.CommandBase.OnExecute() in /home/vsts/work/r1/a/drop/NuKeeper/Commands/CommandBase.cs:line 104
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at NuKeeper.Program.Main(String[] args) in /home/vsts/work/r1/a/drop/NuKeeper/Program.cs:line 33

**Comment by aprice30** [comment]
Issue was related to a corrupt csproj file and NuGet hit the error when updating the file
