### ISSUE TITLE
Error when running repo against private GitLab instance

### ISSUE THREAD

**Issue by paulowens** [NuKeeperDotNet/NuKeeper#905]
## 🐛 Bug Report

Running repo command against a private instance of Gitlab returns the error, 'The provided uri was is not in the correct format.'

### Reproduction steps
Running the following command:
```$ nukeeper repo https://git.acmeaws.io/international/tools/nukeeper-test.git sadfdfddfd --api https://git.acmeaws.io/api/v4 --platform GitLab```

results in the following output:

```
Unhandled Exception: NuKeeper.Abstractions.NuKeeperException: The provided uri was is not in the correct format. Provided https://git.tmaws.io/intl-resale/tools/nukeeper-test.git and format should be https://gitlab.com/{username}/{projectname}.git
   at NuKeeper.Gitlab.GitlabSettingsReader.RepositorySettings(Uri repositoryUri, String targetBranch) in d:\a\r1\a\drop\NuKeeper.Gitlab\GitlabSettingsReader.cs:line 59
   at NuKeeper.Commands.RepositoryCommand.PopulateSettings(SettingsContainer settings) in d:\a\r1\a\drop\NuKeeper\Commands\RepositoryCommand.cs:line 57
   at NuKeeper.Commands.CommandBase.OnExecute() in d:\a\r1\a\drop\NuKeeper\Commands\CommandBase.cs:line 96
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NuKeeper.Program.Main(String[] args) in d:\a\r1\a\drop\NuKeeper\Program.cs:line 33
```

### Configuration

**Version:** 0.26.0

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [ ] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [x] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker

**Comment by Calytic** [comment]
The scope of this issue is greater than private GitLab repositories.  #905 applies to all repositories that do not conform to the "https://gitlab.com/{username}/{projectname}.git" format, meaning all repositories (even public ones) that use subgroups.

A valid gitlab repository url might be:
`https://gitlab.com/{username}/{subgroup}/{projectname}.git`
but that would be considered invalid by nukeeper.

**Comment by Calytic** [comment]
Confirmed: https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper.Gitlab/GitlabSettingsReader.cs#L53

**Comment by overbit** [comment]
Any update on this?
